#on:
#  create:
#    tags:
#      - v*
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#      - name: Build and publish to pypi
#        uses: JRubics/poetry-publish@v1.16
#        with:
#          pypi_token: ${{ secrets.PROD_PYPI}}
#
